spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sgldb
        username: admin
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
jwt:
    secret: EChRhAiO8AuAse52JsR2O86UA1EfmQ3YK3APUr0kBBo=
    expiration-ms: 3600000
sira:
  base-url: http://localhost:3000/api  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html